version: '3.9'
services:
    database:
        build:
            context: ./OpenttdDiscord.Database
            dockerfile: Dockerfile
        volumes:
            - "psql_data:/var/lib/mysql"
        ports:
            - 3306:3306
volumes:
    psql_data: