version: '3.9'
services:
    bot:
        build: .
        environment:
            Database:ConnectionString: User ID=openttd;Password=secret-pw;Host=database;Port=5432;Database=openttd
            Discord:Token: "${discord_token}"
    database:
        build:
            context: ./OpenttdDiscord.Database
            dockerfile: Dockerfile
        volumes:
            - "psql_data:/var/lib/mysql"
        ports:
            - 5432:5432
volumes:
    psql_data: