version: '3.3'
services:
    bot:
        build: .
        environment:
            Database:ConnectionString: User ID=openttd;Password=secret-pw;Host=database;Port=5432;Database=openttd
            Discord:Token: "${discord_token}"
        volumes:
            - "chat_data:/var/app/ottd"
    database:
        build:
            context: ./OpenttdDiscord.Database
            dockerfile: Dockerfile
        volumes:
            - "psql_data:/var/lib/postgresql/data"
        ports:
            - 5432:5432
volumes:
    psql_data:
    chat_data: