FROM postgres:15.1 AS build
# needed for intialization
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=openttd
ENV MYSQL_USER=openttd
ENV MYSQL_PASSWORD=secret-pw
ENV POSTGRES_PASSWORD=secret-pw

# initialize database

#FROM postgres:15.1 AS run
