name: ci
on:
  push:
    branches:
      - master
      - workflow_dispatch
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: |
          cd docs
          pip install mkdocs-material
          pip install mkdocs-roamlinks-plugin
          pip install mkdocs-rss-plugin
          mkdocs gh-deploy --force
      # - run: pip install mkdocs-mermaid2-plugin

